# Generated by Django 5.0.1 on 2024-01-29 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=200)),
                ('pdesc', models.CharField(max_length=500)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('img', models.ImageField(upload_to='uploads')),
            ],
        ),
    ]
